title: Sherin S
description: Sherin S is a Blogger and SEO Analyst and Blogger, This Site is his Portfolio. >  # this means to ignore newlines until "baseurl:"
 
  
baseurl: "/" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':/'
blog_theme: dark # Or use dark

# Profile information
name: Sherin S
tagline: SEO ANALYST
about-description: A Programmer and SEO Analyst by Profession and a Blogger by Passion # Add Discription
pic: 79.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: sherinajumal@gmail.com # Add your Email address
phone: 8089277096  # Add your Phone number
website: mworkbench.com # Add your website, do not add http://
linkedin: sherin-s # Add your Linkedin handle
github: ajumalsherin # Add your Github handle
twitter: '@sherinajumal' # Add your Twitter handle

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
